# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_auto_20160629_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='sensor',
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 9, 50, 39, 767701)),
        ),
    ]
