# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_auto_20160629_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcontroller',
            name='max_distance',
            field=models.IntegerField(verbose_name=' Max Distance to trigger alarm (cm)'),
        ),
        migrations.AlterField(
            model_name='sensorcontroller',
            name='min_distance',
            field=models.IntegerField(verbose_name='Min Distance to trigger alarm (cm)'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 29, 9, 57, 25, 348350)),
        ),
    ]
