# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_auto_20160629_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 29, 10, 11, 34, 466147), null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='distance',
            field=models.FloatField(verbose_name='cm'),
        ),
    ]
