# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_auto_20160629_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 29, 10, 12, 29, 259780), null=True),
        ),
    ]
