# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_remove_sensordata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 29, 10, 17, 1, 674177), null=True),
        ),
    ]
