# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0008_sensordata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='access_control.SensorController'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 29, 10, 22, 26, 812210), null=True),
        ),
    ]
