# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_auto_20160629_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcontroller',
            name='name',
            field=models.CharField(default=1, max_length=80, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 29, 10, 31, 56, 88030), null=True),
        ),
    ]
